In [2]:
import numpy as np
import nltk
from nltk.text import TextCollection
from pymongo import MongoClient
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from numpy import dot
from numpy.linalg import norm

In [3]:
#client = MongoClient("192.168.2.166:30003")
#db=client.crawlerdb # crawl_database_1 is the db name
#collection = db.crawlerdb
#result_documents_list = list(collection.find({})) # find returns cursor, like an iterator in scala

In [4]:
result_documents_list = [{'_id': '5c2b861a7faca327135730a6',
  'date': '27.06.2017',
  'title': 'Ein Schwerverletzter und zwei Leichtverletzte bei Auseinandersetzung',
  'location': 'Mitte',
  'text': 'hallo hier bin In der Nacht kam es in Mitte zu einer Auseinandersetzung zwischen mehreren Personen, bei der drei Männer verletzt wurden. Ersten Ermittlungen zufolge sollen sich die drei Verletzten, im Alter von 18, 20 und 21 Jahren, gemeinsam mit Freunden und ihnen Unbekannten gegen Mitternacht am Neptunbrunnen in der Spandauer Straße aufgehalten haben. Plötzlich habe ein Unbekannter eine Glasfasche geworfen, die jedoch niemanden traf. Daraufhin sei es zu einem Handgemenge gekommen, in dessen Verlauf zwei Männer Reizgas versprühten. Die beiden 18 und 20 Jahre alten Männer erlitten leichte Augenreizungen, die zum Teil ambulant von alarmierten Rettungskräften behandelt wurden. Im Zuge der Anzeigenaufnahme erfuhren die Beamten, dass unter der Liebknechtbrücke der 21-Jährige liege, der eine Schnittwunde aufwies. Diese habe er von einem ihm namentlich nicht bekannten Mann im Anschluss an das Handgemenge mit einem Messer zugefügt bekommen. Rettungskräfte brachten den Schwerverletzten zur\n    stationären Behandlung in eine Klinik. Die genauen Hintergründe der Tat sind nun Teil der Ermittlungen, die die Kriminalpolizei der Direktion 3 führt.',
  'number': ['Nr. 1431', '']},
 {'_id': '5c2b861a7faca327135730a7',
  'date': '17.07.2017',
  'title': 'Ein Krankenwagenunfall',
  'location': 'Osten',
  'text': 'Während des Tages kam es in Mitte zu einer Auseinandersetzung zwischen mehreren Personen, bei der drei Männer verletzt wurden. Ersten Ermittlungen zufolge sollen sich die drei Verletzten, im Alter von 18, 20 und 21 Jahren, gemeinsam mit Freunden und ihnen Unbekannten gegen Mitternacht am Neptunbrunnen in der Spandauer Straße aufgehalten haben. Plötzlich habe ein Unbekannter eine Glasfasche geworfen, die jedoch niemanden traf. Daraufhin sei es zu einem Handgemenge gekommen, in dessen Verlauf zwei Männer Reizgas versprühten. Die beiden 18 und 20 Jahre alten Männer erlitten leichte Augenreizungen, die zum Teil ambulant von alarmierten Rettungskräften behandelt wurden. Im Zuge der Anzeigenaufnahme erfuhren die Beamten, dass unter der Liebknechtbrücke der 21-Jährige liege, der eine Schnittwunde aufwies. Diese habe er von einem ihm namentlich nicht bekannten Mann im Anschluss an das Handgemenge mit einem Messer zugefügt bekommen. Rettungskräfte brachten den Schwerverletzten zur\n    stationären Behandlung in eine Klinik. Die genauen Hintergründe der Tat sind nun Teil der Ermittlungen, die die Kriminalpolizei der Direktion 3 führt.',
  'number': ['Nr. 1430', '']},
 {'_id': '5c2b861a7faca327135730a8',
  'date': '16.07.2017',
  'title': 'Feuer in einem Haus',
  'location': 'Westen',
  'text': 'Während des Tages kam es in Mitte zu einem Konflikt zwischen mehreren Personen, bei der drei Männer verletzt wurden. Ersten Ermittlungen zufolge sollen sich die drei Verletzten, im Alter von 18, 20 und 21 Jahren, gemeinsam mit Freunden und ihnen Unbekannten gegen Mitternacht am Neptunbrunnen in der Spandauer Straße aufgehalten haben. Plötzlich habe ein Unbekannter eine Glasfasche geworfen, die jedoch niemanden traf. Daraufhin sei es zu einem Handgemenge gekommen, in dessen Verlauf zwei Männer Reizgas versprühten. Die beiden 18 und 20 Jahre alten Männer erlitten leichte Augenreizungen, die zum Teil ambulant von alarmierten Rettungskräften behandelt wurden. Im Zuge der Anzeigenaufnahme erfuhren die Beamten, dass unter der Liebknechtbrücke der 21-Jährige liege, der eine Schnittwunde aufwies. Diese habe er von einem ihm namentlich nicht bekannten Mann im Anschluss an das Handgemenge mit einem Messer zugefügt bekommen. Rettungskräfte brachten den Schwerverletzten zur\n    stationären Behandlung in eine Klinik. Die genauen Hintergründe der Tat sind nun Teil der Ermittlungen, die die Kriminalpolizei der Direktion 3 führt.',
  'number': ['Nr. 1432', '1430']},
 {'_id': '5c2b861a7faca327135730a9',
  'date': '17.07.2017',
  'title': 'Feuer in einem Haus',
  'location': 'Westen',
  'text': 'Während des Tages kam es in Mitte zu einem Konflikt zwischen einer Person, bei der 4 Männer verletzt wurden. Ersten Ermittlungen zufolge sollen sich die drei Verletzten, im Alter von 18, 20 und 21 Jahren, gemeinsam mit Freunden und ihnen Unbekannten gegen Mitternacht am Neptunbrunnen in der Spandauer Straße aufgehalten haben. Plötzlich habe ein Unbekannter eine Glasfasche geworfen, die jedoch niemanden traf. Daraufhin sei es zu einem Handgemenge gekommen, in dessen Verlauf zwei Männer Reizgas versprühten. Die beiden 18 und 20 Jahre alten Männer erlitten leichte Augenreizungen, die zum Teil ambulant von alarmierten Rettungskräften behandelt wurden. Im Zuge der Anzeigenaufnahme erfuhren die Beamten, dass unter der Liebknechtbrücke der 21-Jährige liege, der eine Schnittwunde aufwies. Diese habe er von einem ihm namentlich nicht bekannten Mann im Anschluss an das Handgemenge mit einem Messer zugefügt bekommen. Rettungskräfte brachten den Schwerverletzten zur\n    stationären Behandlung in eine Klinik. Die genauen Hintergründe der Tat sind nun Teil der Ermittlungen, die die Kriminalpolizei der Direktion 3 führt.',
  'number': ['Nr. 1428', '']},
 {'_id': '5c2b861a7faca327135730aa',
  'date': '15.07.2017',
  'title': 'Feuer in einem Haus',
  'location': 'Norden',
  'text': 'Während des Tages kam es in Mitte zu einem Konflikt zwischen einer Person, bei der 4 Männer verwunded wurden. Ersten Ermittlungen zufolge sollen sich die drei Verletzten, im Alter von 18, 20 und 21 Jahren, gemeinsam mit Freunden und ihnen Unbekannten gegen Mitternacht am Neptunbrunnen in der Spandauer Straße aufgehalten haben. Plötzlich habe ein Unbekannter eine Glasfasche geworfen, die jedoch niemanden traf. Daraufhin sei es zu einem Handgemenge gekommen, in dessen Verlauf zwei Männer Reizgas versprühten. Die beiden 18 und 20 Jahre alten Männer erlitten leichte Augenreizungen, die zum Teil ambulant von alarmierten Rettungskräften behandelt wurden. Im Zuge der Anzeigenaufnahme erfuhren die Beamten, dass unter der Liebknechtbrücke der 21-Jährige liege, der eine Schnittwunde aufwies. Diese habe er von einem ihm namentlich nicht bekannten Mann im Anschluss an das Handgemenge mit einem Messer zugefügt bekommen. Rettungskräfte brachten den Schwerverletzten zur\n    stationären Behandlung in eine Klinik. Die genauen Hintergründe der Tat sind nun Teil der Ermittlungen, die die Kriminalpolizei der Direktion 3 führt.',
  'number': ['Nr. 1427', '']}]

In [5]:
result_document_text_list = corpus = [a["text"] for a in result_documents_list]

In [6]:
search_term = ["hallo hier bin ich"]

In [13]:
tfidf = TfidfVectorizer()
tfidf_values = tfidf.fit_transform(corpus)
pd.DataFrame(tfidf_values.todense(),columns=tfidf.get_feature_names())

,18,20,21,alarmierten,alten,alter,am,ambulant,an,anschluss,...,wurden,während,zu,zufolge,zuge,zugefügt,zum,zur,zwei,zwischen
0,0.100629,0.100629,0.100629,0.050314,0.050314,0.050314,0.050314,0.050314,0.050314,0.050314,...,0.100629,0.000000,0.100629,0.050314,0.050314,0.050314,0.050314,0.050314,0.050314,0.050314
1,0.104427,0.104427,0.104427,0.052213,0.052213,0.052213,0.052213,0.052213,0.052213,0.052213,...,0.104427,0.061733,0.104427,0.052213,0.052213,0.052213,0.052213,0.052213,0.052213,0.052213
2,0.103762,0.103762,0.103762,0.051881,0.051881,0.051881,0.051881,0.051881,0.051881,0.051881,...,0.103762,0.061340,0.103762,0.051881,0.051881,0.051881,0.051881,0.051881,0.051881,0.051881
3,0.104140,0.104140,0.104140,0.052070,0.052070,0.052070,0.052070,0.052070,0.052070,0.052070,...,0.104140,0.061563,0.104140,0.052070,0.052070,0.052070,0.052070,0.052070,0.052070,0.052070
4,0.103718,0.103718,0.103718,0.051859,0.051859,0.051859,0.051859,0.051859,0.051859,0.051859,...,0.103718,0.061314,0.103718,0.051859,0.051859,0.051859,0.051859,0.051859,0.051859,0.051859

In [14]:
tfidf_search_term = tfidf.transform(search_term)
#pd.DataFrame(tfidf_search_term.todense(),columns=tfidf.get_feature_names())
tfidf_search_term.todense()

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
for i in range(5):
    tfidf_values_tmp = np.array(tfidf_values.todense()[i]).reshape(-1)
    tfidf_search_term_tmp = np.array(tfidf_search_term.todense()).reshape(-1)
    
    first = np.dot(tfidf_values_tmp, tfidf_search_term_tmp)
    second = (norm(tfidf_values_tmp)*norm(tfidf_search_term_tmp))
    print(norm(tfidf_search_term_tmp)) # norm des search_term*s ist 0 deshalb ist second 0, deshalb wird durch 0 geteilt, deshalb ist result nan
    cos_sim = first * 1.0/second
    print(cos_sim)

0.0
nan
0.0
nan
0.0
nan
0.0
nan
0.0
nan

/home/flo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in double_scalars